myenv/Travel/Travel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('all_contry/', include('trvapp.urls',namespace='Travel')),
    path('features/', include('tavelfeatures.urls',namespace='features')),
    path('food-and-drink/',include('foodanddrink.urls',namespace='foodanddrink'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myenv/Travel/foodanddrink/urls.py
from django.conf.urls import url
from . import views
app_name='foodanddrink'
urlpatterns = [
url(r'^$',views.all_food_and_drink,name='all_food_and_drink'),
url(r'^(?P<slug>[-\w]+)$',views.det_food,name='det_food'),

]

myenv/Travel/tavelfeatures/urls.py
from django.conf.urls import url
from . import views
app_name='tavelfetuers'
urlpatterns = [
    url(r'^$',views.all_fetuers,name='all_fetuers'),
    url(r'^(?P<slug>[-\w]+)',views.all_detail,name='all_detail'),
]

myenv/Travel/trvapp/urls.py
from django.conf.urls import url
from . import views
app_name='trvapp'
urlpatterns = [
    url(r'^$',views.all_contry,name='all_contr'),
    url(r'^(?P<slug>[-\w]+)$',views.detail_contry,name='detail_contry'),
    url(r'^(?P<slug>[-\w]+)/pictuers$',views.image_contry,name='image_contry'),
    url(r'^(?P<slug>[-\w]+)/history$',views.history_contry,name='history_contry'),
    url(r'^(?P<slug>[-\w]+)/wather-geography$',views.wather_geograohy,name='wather_geograohy'),
    url(r'^(?P<slug>[-\w]+)/Image-Food$',views.Image_food,name='Image_food'),
    ]

myenv/Travel/templates/base.html
{% load static %}
	<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static '/image_static/images/1.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="Colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->

		<link rel="shortcut icon" href="{% static 'image_static/images/favicon.ico' %}" type="image/x-icon">
		<link rel="apple-touch-icon" href="{% static 'image_static/images/apple-touch-icon.png' %}">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'image_static/css/bootstrap.min.css' %}">
		<!-- Pogo Slider CSS -->
		<link rel="stylesheet" href="{% static 'image_static/css/pogo-slider.min.css' %}">
	<!-- Site CSS
		<link rel="stylesheet" href="{% static 'image_static/css/style.css' %}">
		<!- Responsive CSS -->
		<link rel="stylesheet" href="{% static 'image_static/css/responsive.css' %}">
		<!-- Custom CSS -->
		<link rel="stylesheet" href="{% static 'image_static/css/custom.css' %}">

      """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
			<link rel="stylesheet" href="{% static '/home-static/css/linearicons.css' %}">
			<link rel="stylesheet" href="{% static '/home-static/css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static '/home-static/css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static '/home-static/css/nice-select.css' %}">
			<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
			<link rel="stylesheet" href="{% static '/home-static/css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static '/home-static/css/main.css' %}">
		</head>
		<body>


			<!-- Start Header Area -->
			<header class="default-header">
				<div class="container">
					<div class="header-wrap">
						<div class="header-top d-flex justify-content-between align-items-center">
							<div class="logo">
								<a href="{% url 'Travel:all_contr' %}"><img src="{% static 'home-static/img/logoo.png' %}" width=60px alt=""> Travel and Tourism</a>
							</div>
							<div class="main-menubar d-flex align-items-center">
								<nav class="hide">
									<a href="{% url 'Travel:all_contr' %}">Home</a>

									<a href="{% url 'features:all_fetuers' %}">features</a>
									<a href="{% url 'foodanddrink:all_food_and_drink' %}">food and drink</a>

								</nav>
								<div class="menu-bar"><span class="lnr lnr-menu"></span></div>
							</div>
						</div>
					</div>
				</div>
			</header>

			<!-- End Header Area -->

   {%  block body %}


   {% endblock %}
<!-- start footer Area -->
<footer class="footer-area section-gap">
  <div class="container">
    <div class="row">


      <div class="col-lg-6  col-md-12">
        <div class="single-footer-widget newsletter">
          <h6>About The World Travel Guide</h6>
          <p>The World Travel Guide (WTG) is the flagship digital consumer brand within the Columbus Travel Media portfolio. A comprehensive guide to the world’s best travel destinations, its print heritage stretches back more than 30 years, with the online portal reaching its 20-year anniversary in 2019. Available in English, German and Spanish versions, the WTG provides detailed and accurate travel content designed to inspire global travellers. It covers all aspects, from cities to airports, cruise ports to ski and beach resorts, attractions to events, and it also includes weekly travel news, features and quizzes. Updated every day by a dedicated global editorial team, the portal logs 1 million+ unique users monthly.</p>

        </div>
      </div>
    </div>

    <div class="row footer-bottom d-flex justify-content-between">
      <p class="col-lg-8 col-sm-12 footer-text m-0">
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </p>

    </div>
  </div>
</footer>
<!-- End footer Area -->


    <script src="{% static 'home-static/js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{% static 'home-static/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.sticky.js' %}"></script>
    <script src="{% static 'home-static/js/parallax.min.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'home-static/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home-static/js/waypoints.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home-static/js/main.js' %}"></script>
    wait....................................................................

		<script src="{% static 'image_static/js/jquery.pogo-slider.min.js' %}"></script>
		<script src="{% static 'image_static/js/slider-index.js' %}"></script>
		<script src="{% static 'image_static/js/smoothscroll.js' %}"></script>
		<script src="{% static 'image_static/js/form-validator.min.js' %}"></script>
		<script src="{% static 'image_static/js/contact-form-script.js' %}"></script>
	  <script src="{% static 'image_static/js/custom.js' %}"></script>
     </body>
   </html>

myenv/Travel/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block body %}
	<title>all contries</title>
<section class="banner-area relative" id="home">
  <div class="container">
      <div class="row fullscreen align-items-center justify-content-center">
        <div class="banner-content col-lg-6 col-md-30">
          <h1 class="text-uppercase">
           Editorial Foreword	 <br>

          </h1>
          <p>
            The World Travel Guide (WTG) is the flagship digital consumer brand within the Columbus Travel Media portfolio. Available in English, German, and Spanish versions, the WTG provides detailed and accurate travel content designed to inspire global travellers. It covers all aspects, from cities to airports, cruise ports to ski and beach resorts, attractions to events, and it also includes offbeat travel news, stories, quizzes and guides for adventurous travellers.
          </p>
                </div>
        <div class="col-lg-6 d-flex align-self-end img-right">
          <img class="img-fluid" src="{% static 'home-static/img/header-img.jpg' %}" alt="">
        </div>
      </div>
  </div>
</section>

<section class="feature-area section-gap" id="service">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="single-feature d-flex flex-row pb-30">

  </div>
</section>

<section class="blog-area section-gap">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 pb-30 header-text">
        <h1>Directory of countries</h1>
        <p>

        </p>
      </div>
    </div>

    <div class="row">
      {% for i in file %}
      <div class="single-blog col-lg-4 col-md-4">

        <img class="f-img img-fluid mx-auto" src={{i.img.url}} alt="">
        <h4>
          <a href="{% url 'Travel:detail_contry' i.slug %}">{{i.contry_name}}</a>
        </h4>
        <p>
          {{i.about|truncatewords:25}}
        </p>
      </div>
        {% endfor %}
    </div>

  </div>
</section>
{% endblock %}