myenv/Travel/Travel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('all_contry/', include('trvapp.urls',namespace='Travel')),
    path('features/', include('tavelfeatures.urls',namespace='features')),
    path('food-and-drink/',include('foodanddrink.urls',namespace='foodanddrink'))
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myenv/Travel/trvapp/urls.py
from django.conf.urls import url
from . import views
app_name='trvapp'
urlpatterns = [
    url(r'^$',views.all_contry,name='all_contr'),
    url(r'^(?P<slug>[-\w]+)$',views.detail_contry,name='detail_contry'),
    url(r'^(?P<slug>[-\w]+)/pictuers$',views.image_contry,name='image_contry'),
    url(r'^(?P<slug>[-\w]+)/history$',views.history_contry,name='history_contry'),
    url(r'^(?P<slug>[-\w]+)/wather-geography$',views.wather_geograohy,name='wather_geograohy'),
    url(r'^(?P<slug>[-\w]+)/Image-Food$',views.Image_food,name='Image_food'),
    ]

myenv/Travel/trvapp/models.py
from django.db import models
from django.utils.text import slugify
import datetime
class Contry(models.Model):
    contry_name=models.CharField(max_length=30)
    slug=models.SlugField(blank=True,null=True)
    about=models.TextField(blank=True,null=True)
    history=models.TextField(blank=True,null=True)
    langunge=models.TextField(blank=True,null=True)
    culture=models.TextField(blank=True,null=True)
    wather=models.TextField(blank=True,null=True)
    geography=models.TextField(blank=True,null=True)
    img=models.ImageField(upload_to='photo')
    #######################################
    created=models.DateTimeField(default=datetime.datetime.now)
    #########################################
    tag1=models.CharField(max_length=100)
    tag2=models.CharField(max_length=100)
    tag3=models.CharField(max_length=100)
    tag4=models.CharField(max_length=100)
    tag5=models.CharField(max_length=100)
    tag6=models.CharField(max_length=100)
    ##########################################
    img2=models.ImageField(upload_to='photo')
    img3=models.ImageField(upload_to='photo')
    img4=models.ImageField(upload_to='photo')
    img5=models.ImageField(upload_to='photo')
    img6=models.ImageField(upload_to='photo')
    img7=models.ImageField(upload_to='photo')

    ###########################

    img22=models.ImageField(upload_to='photo')
    img33=models.ImageField(upload_to='photo')
    img44=models.ImageField(upload_to='photo')
    img55=models.ImageField(upload_to='photo')
    img66=models.ImageField(upload_to='photo')
    img77=models.ImageField(upload_to='photo')

    ##########################
    tag11=models.CharField(max_length=100 ,blank=True)
    tag22=models.CharField(max_length=100,blank=True)
    tag33=models.CharField(max_length=100,blank=True)
    tag44=models.CharField(max_length=100,blank=True)
    tag55=models.CharField(max_length=100,blank=True)
    tag66=models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.contry_name
    def save(self,*ags,**kwargs):
        if not self.slug :
            self.slug=slugify(self.contry_name)
        return super(Contry,self).save(*ags,**kwargs)

myenv/Travel/trvapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Contry
# Create your views here.
def all_contry(request):
    file=Contry.objects.all()
    context={'file':file}
    return render(request,'home.html',context)

def detail_contry(request,slug):
    file=get_object_or_404(Contry,slug=slug)
    context={'file':file}
    return render(request,'detail.html',context)
def image_contry(request,slug):
    imgs=get_object_or_404(Contry,slug=slug)
    context={'imgs':imgs}
    return render(request,'images.html',context)
def history_contry(request,slug):
    hi=get_object_or_404(Contry,slug=slug)
    context={'hi':hi}
    return render(request,'hestory.html',context)
def wather_geograohy(request,slug):
    wage=get_object_or_404(Contry,slug=slug)
    context={'wage':wage}
    return render(request,'wather.html',context)

def Image_food(request,slug):
    I=get_object_or_404(Contry,slug=slug)
    context={'I':I}
    return render(request,'Image_food.html',context)

myenv/Travel/trvapp/templates/Image_food.html
{% extends 'base.html' %}
{% load static %}
{% block body %}



<title>image {{I.contry_name}}</title>
<body id="home" data-spy="scroll" data-target="#navbar-wd" data-offset="98">

<!-- LOADER -->
  <div id="preloader">
  <div class="preloader pulse">
    <i class="fa fa-heartbeat" aria-hidden="true"></i>
  </div>
  </div><!-- end loader -->
  <!-- END LOADER -->


<!-- Start Banner -->
<div class="ulockd-home-slider">
  <div class="container-fluid">
    <div class="row">
      <div class="pogoSlider" id="js-main-slider">

        <div class="pogoSlider-slide" data-transition="zipReveal" data-duration="1500" style="background-image:url({{I.img22.url}});">

        </div>
        <div class="pogoSlider-slide" data-transition="shrinkReveal" data-duration="2000" style="background-image:url({{I.img33.url}});">
          <div class="lbox-caption">
            <div class="lbox-details">

            </div>
          </div>

        </div>
        <div class="pogoSlider-slide" data-transition="shrinkReveal" data-duration="2000" style="background-image:url({{I.img44.url}});">
          <div class="lbox-caption">
            <div class="lbox-details">

            </div>
          </div>

        </div>
        <div class="pogoSlider-slide" data-transition="shrinkReveal" data-duration="2000" style="background-image:url({{I.img55.url}});">
          <div class="lbox-caption">
            <div class="lbox-details">

            </div>
          </div>

        </div>
        <div class="pogoSlider-slide" data-transition="shrinkReveal" data-duration="2000" style="background-image:url({{I.img66.url}});">
          <div class="lbox-caption">
            <div class="lbox-details">

            </div>
          </div>

        </div>


      </div><!-- .pogoSlider -->
    </div>
  </div>
</div>
<!-- End Banner -->



<!-- Start Family -->
<div id="family" class="family-box">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="title-box">
          <br>
          <h2>Images for {{I.contry_name|capfirst}}</h2>
          <p>Pictures of lash food </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="single-team-member">
          <div class="family-img">
            <img class="img-fluid" src="{{I.img22.url}}" alt="" />
          </div>
          <div class="family-info">
            <h4>{{I.tag11}}</h4>
            <p>Published: {{I.created}}</p>
            <br>

          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="single-team-member">
          <div class="family-img">
            <img class="img-fluid" src="{{I.img33.url}}" alt="" />
          </div>
          <div class="family-info">
            <h4>{{I.tag22}} </h4>
              <p>Published: {{I.created}}</p>
            <br>

          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="single-team-member">
          <div class="family-img">
            <img class="img-fluid" src="{{I.img44.url}}" alt="" />
          </div>
          <div class="family-info">
            <h4>{{I.tag33}}</h4>
              <p>Published: {{I.created}}</p>
            <br>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="single-team-member">
          <div class="family-img">
            <img class="img-fluid" src="{{I.img55.url}}" alt="" />
          </div>
          <div class="family-info">
            <h4>{{I.tag44}}</h4>
              <p>Published: {{I.created}}</p>
          <br>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="single-team-member">
          <div class="family-img">
            <img class="img-fluid" src="{{I.img66.url}}" alt="" />
          </div>
          <div class="family-info">
            <h4>{{I.tag55}}</h4>
              <p>Published: {{I.created}}</p>
        <br>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
<!-- End Family -->


<!-- ALL JS FILES -->

</body>

{% endblock %}

myenv/Travel/trvapp/templates/detail.html
{% extends "base.html"%}
{% load static %}
<!doctype html>
{% block body %}
	<title>{{file.contry_name}}</title>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
    <div id="overlayer"></div>
    <div class="site-wrap" id="home-section">
      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>
      <div class="block__73694 site-section border-top" id="why-us-section">
        <div class="container">
          <div class="row d-flex no-gutters align-items-stretch">
            <div class="col-12 col-lg-6 block__73422 order-lg-2" style="background-image:" data-aos="fade-left" data-aos-delay="">
             <img src="{{file.img.url}}" width=600px>
            </div>
            <div class="col-lg-5 mr-auto p-lg-5 mt-4 mt-lg-0 order-lg-1" data-aos="fade-right" data-aos-delay="">
              <h2 class="mb-4 text-black">{{file.contry_name}} travel guide</h2>
              <h4 class="text-primary">About {{file.contry_name}}</h4>
              <p>{{file.about}}</p>

              <ul class="ul-check primary list-unstyled mt-5">
                <li><a href="{% url 'Travel:image_contry' file.slug %}">image for this contry</a></li>
                <li><a href="{% url 'Travel:history_contry' file.slug %}">history & langunge & culture for this contry</a></li>
                <li><a href="{% url 'Travel:wather_geograohy' file.slug %}">weather & geography for this contry</a></li>
								  <li><a href="{% url 'Travel:Image_food' file.slug %}">Pictures of lash food</a></li>

              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>

  {% endblock %}

myenv/Travel/trvapp/templates/hestory.html
{% extends "base.html" %}
{% load static %}
{% block body %}
	<title>history {{hi.contry_name}}</title>
    <section class="home-about spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="about-text">
											<br><br>
                        <h2>A brief history of {{hi.contry_name}} , language and culture</h2><br><h4>history of {{hi.contry_name|capfirst}}</h4>
                        <p class="short-details">{{hi.history|capfirst}}</p><br>
                        <h4>langunge of {{hi.contry_name|capfirst}}</h4>
                        <p class="long-details">{{hi.langunge|capfirst}}</p><br>
                          <h4>culture of {{hi.contry_name|capfirst}}</h4>
                          <p class="long-details">{{hi.culture|capfirst}}</p><br>

                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-img">
                        <img src="{{hi.img.url}}" width=450px alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

myenv/Travel/trvapp/templates/images.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>

<html lang="en"><!-- Basic -->

<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

     <!-- Site Metas -->
    <title>The Real Wedding - Responsive OnePage HTML5 Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

		<!-- Site Icons -->


    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
{% block body %}
	<title>image {{imgs.contry_name}}</title>
<body id="home" data-spy="scroll" data-target="#navbar-wd" data-offset="98">

	<!-- LOADER -->
    <div id="preloader">
		<div class="preloader pulse">
			<i class="fa fa-heartbeat" aria-hidden="true"></i>
		</div>
    </div><!-- end loader -->
    <!-- END LOADER -->


	<!-- Start Banner -->
	<div class="ulockd-home-slider">
		<div class="container-fluid">
			<div class="row">
				<div class="pogoSlider" id="js-main-slider">

					<div class="pogoSlider-slide" data-transition="zipReveal" data-duration="1500" style="background-image:url({{imgs.img2.url}});">

					</div>
					<div class="pogoSlider-slide" data-transition="shrinkReveal" data-duration="2000" style="background-image:url({{imgs.img3.url}});">
						<div class="lbox-caption">
							<div class="lbox-details">

							</div>
						</div>

					</div>
					<div class="pogoSlider-slide" data-transition="shrinkReveal" data-duration="2000" style="background-image:url({{imgs.img4.url}});">
						<div class="lbox-caption">
							<div class="lbox-details">

							</div>
						</div>

					</div>
					<div class="pogoSlider-slide" data-transition="shrinkReveal" data-duration="2000" style="background-image:url({{imgs.img5.url}});">
						<div class="lbox-caption">
							<div class="lbox-details">

							</div>
						</div>

					</div>
					<div class="pogoSlider-slide" data-transition="shrinkReveal" data-duration="2000" style="background-image:url({{imgs.img6.url}});">
						<div class="lbox-caption">
							<div class="lbox-details">

							</div>
						</div>

					</div>


				</div><!-- .pogoSlider -->
			</div>
		</div>
	</div>
	<!-- End Banner -->



	<!-- Start Family -->
	<div id="family" class="family-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="title-box">
						<br>
						<h2>Images for {{imgs.contry_name|capfirst}}</h2>
						<p>The most important religious and archaeological sights. </p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4 col-md-6 col-sm-12">
					<div class="single-team-member">
						<div class="family-img">
							<img class="img-fluid" src="{{imgs.img2.url}}" alt="" />
						</div>
						<div class="family-info">
							<h4>{{imgs.tag1}}</h4>
							<p>Published: {{imgs.created}}</p>
							<br>

						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-12">
					<div class="single-team-member">
						<div class="family-img">
							<img class="img-fluid" src="{{imgs.img3.url}}" alt="" />
						</div>
						<div class="family-info">
							<h4>{{imgs.tag2}} </h4>
								<p>Published: {{imgs.created}}</p>
							<br>

						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-12">
					<div class="single-team-member">
						<div class="family-img">
							<img class="img-fluid" src="{{imgs.img4.url}}" alt="" />
						</div>
						<div class="family-info">
							<h4>{{imgs.tag3}}</h4>
								<p>Published: {{imgs.created}}</p>
							<br>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-12">
					<div class="single-team-member">
						<div class="family-img">
							<img class="img-fluid" src="{{imgs.img5.url}}" alt="" />
						</div>
						<div class="family-info">
							<h4>{{imgs.tag4}}</h4>
								<p>Published: {{imgs.created}}</p>
						<br>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-12">
					<div class="single-team-member">
						<div class="family-img">
							<img class="img-fluid" src="{{imgs.img6.url}}" alt="" />
						</div>
						<div class="family-info">
							<h4>{{imgs.tag5}}</h4>
								<p>Published: {{imgs.created}}</p>
					<br>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
	<!-- End Family -->


	<!-- ALL JS FILES -->

</body>

</html>
{% endblock %}

myenv/Travel/trvapp/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body %}
			<section class="banner-area relative" id="home">
				<div class="container">
						<div class="row fullscreen align-items-center justify-content-center">
							<div class="banner-content col-lg-6 col-md-12">
								<h1 class="text-uppercase">
								 Editorial Foreword	 <br>

								</h1>
								<p>
								  The World Travel Guide (WTG) is the flagship digital consumer brand within the Columbus Travel Media portfolio. Available in English, German, and Spanish versions, the WTG provides detailed and accurate travel content designed to inspire global travellers. It covers all aspects, from cities to airports, cruise ports to ski and beach resorts, attractions to events, and it also includes offbeat travel news, stories, quizzes and guides for adventurous travellers.
								</p>
											</div>
							<div class="col-lg-6 d-flex align-self-end img-right">
								<img class="img-fluid" src="{% static 'home-static/img/header-img.jpg' %}" alt="">
							</div>
						</div>
				</div>
			</section>

			<section class="feature-area section-gap" id="service">
				<div class="container">
					<div class="row">
						<div class="col-lg-6">
							<div class="single-feature d-flex flex-row pb-30">

				</div>
			</section>

			<section class="blog-area section-gap">
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-md-8 pb-30 header-text">
							<h1>Directory of countries</h1>
							<p>
							
							</p>
						</div>
					</div>

					<div class="row">
						{% for i in file %}
						<div class="single-blog col-lg-4 col-md-4">

							<img class="f-img img-fluid mx-auto" src={{i.img.url}} alt="">
							<h4>
								<a href="{% url 'Travel:detail_contry' i.slug %}">{{i.contry_name}}</a>
							</h4>
							<p>
								{{i.about|truncatewords:25}}
							</p>
						</div>
							{% endfor %}
					</div>

				</div>
			</section>
{%endblock%}

myenv/Travel/trvapp/templates/wather.html
{% extends "base.html" %}
{% load static %}
{% block body %}
	<title>Weather and geography {{wage.contry_name}}</title>
    <section class="home-about spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="about-text">
											<br><br>
                        <h2>Weather and geography of {{wage.contry_name}}</h2><br>

                        <h4>Weather of {{wage.contry_name}}</h4>
                        <p class="long-details">{{wage.wather|capfirst}}</p><br>
                          <h4>geography of {{wage.contry_name}}</h4>
                          <p class="long-details">{{wage.geography|capfirst}}</p><br>

                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-img">
                        <img src="{{wage.img.url}}" width=450px alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}